### ISSUE TITLE
Get more placeholders

### ISSUE THREAD

**Issue by CyriacF** [derklaro/ps-system#34]
Can i add status of the server (for cloudnet) and slots ? Thanks for help !

![image](https://user-images.githubusercontent.com/49961233/135772476-fca5dfa2-097f-4d4e-b1d3-d239d22cf68b.png)

**Comment by derklaro** [comment]
We could add these information to the cloud service class then, which requires a bridge to cloudnet 2. I (or you if you want to) can look into this in the next few days. A quick feedback if you want to do this (or a list of placeholders you want) would be useful :)

**Comment by CyriacF** [comment]
Add basic Cloudnet placeholders, e.g. cloudnet status, motd, number of slots, maximum number of slots...
